// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using desafioBluetooth.Models;

#nullable disable

namespace desafioBluetooth.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20230530141430_CriarBanco")]
    partial class CriarBanco
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("desafioBluetooth.Models.bluetoothModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ApplicationUserId");

                    b.Property<DateTime>("DataHoraEvento")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataHoraEvento");

                    b.Property<bool>("FlagProcess")
                        .HasColumnType("bit")
                        .HasColumnName("FlagProcess");

                    b.Property<string>("MAC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MAC");

                    b.Property<string>("MACPaired")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MACPaired");

                    b.Property<string>("MACScan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MACScan");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Periodo");

                    b.HasKey("Id");

                    b.ToTable("BluetoothDeviceMobile");
                });
#pragma warning restore 612, 618
        }
    }
}
